[package]
name = "porcupine"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "porcupine"
path = "src/main.rs"

[dependencies]
movegen = { path = "ferrum-movegen", package = "ferrum-movegen" }
binread = "2"
smallvec = "1.13"

[workspace]
members = [
    "ferrum-movegen"
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
debug = false


[profile.release.build-override]
opt-level = 3


